import initScrollSuave from "./js/modulos/scroll-suave.js";
import initAnimacaoScroll from "./js/modulos/animacao-scroll.js";
import initAccordion from "./js/modulos/acordion.js";
import initTabNav from "./js/modulos/anima-tab.js";
import initModal from "./js/modulos/modal.js";
import initTooltip from "./js/modulos/tooltip.js";
import initDropdownMenu from "./js/modulos/dropdown-menu.js";
import initMenuMobile from "./js/modulos/menu-mobile.js";
import initAnimaNumeros from "./js/modulos/anima-numeros.js";
import initFuncionamento from "./js/modulos/funcionamento.js";

initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();